### ISSUE TITLE
not able to handle post request 

### ISSUE THREAD

**Issue by Farazrabbani4687** [ourtecads/FaucetPay-Deposit-API-PHP#1]
i am not able to handle the post request, when i pass the token value externally the callback code is executing but when i set the post callback directly from faucetpay then my callback code is not working i am not able to figure it out..and what do you mean by this

$token = $_POST['token']; //need generate token from your server (optional)

`<?php
include 'db.php';
$token=$_POST['token'];
$payment_get = file_get_contents('https://faucetpay.io/merchant/get-payment/'.$token);
$payment_fetch=json_decode($payment_get,true);
$token_status = $payment_fetch['valid'];

$merchant_username = $payment_fetch['merchant_username']; 
$amount1 = $payment_fetch['amount1']; 
$currency1 = $payment_fetch['currency1']; 
$amount2 = $payment_fetch['amount2'];
$currency2 = $payment_fetch['currency2']; 
$custom = $payment_fetch['custom']; 
$my_username = "farazrabbani4687";

//validate request if match with order
if ($my_username == $merchant_username && $token_status == true)
{
    echo "Success";
    $success_insert="INSERT INTO `orders` (`order_id`) VALUES (1)";
    $success_quer=mysqli_query($conn,$success_insert);
    
}
else
{
    echo "Failed";
     $failed_insert="INSERT INTO `orders` (`order_id`) VALUES (0)";
    $failed_quer=mysqli_query($conn,$failed_insert);
}

 
?>`

**Comment by ourtecads** [comment]
have you asked for merchant api access to faucetpay..? Has your account been approved to use it?

**Comment by Farazrabbani4687** [comment]
my issue is solved i was using mysqli to access database now i am using pdo now its working..Thank you
