### ISSUE TITLE
phpmailer is not working in faucetpay callback

### ISSUE THREAD

**Issue by Farazrabbani4687** [ourtecads/FaucetPay-Deposit-API-PHP#2]
I am trying to use phpmailer in faucetpay callback file to notify user that payment is successful,but its not working i am  not getting any email.No errors are `Generated`.Kindly help me with this

my code :
i have removed my personal credentials for security  purpose
`<?php
include 'db.php';
use PHPMailer\PHPMailer\PHPMailer;

//connecting the smtp,execption,phpmailer components
require 'phpmailer/src/Exception.php';
require 'phpmailer/src/SMTP.php';
require 'phpmailer/src/PHPMailer.php';

 $mail=new PHPMailer(true);
$mail->isSMTP();
$mail->Host = 'my host';
$mail->SMTPAuth   = true; 
$mail->Username = 'my username';
$mail->Password = 'my password';
$mail->SMTPSecure = 'ssl';   
$mail->Port = 465;
$mail->setFrom('admin@domain.com', 'Faraz '); 

$token=$_POST['token'];
$payment_get = file_get_contents('https://faucetpay.io/merchant/get-payment/'.$token);
$payment_fetch=json_decode($payment_get,true);
$token_status = $payment_fetch['valid'];

$merchant_username = $payment_fetch['merchant_username']; 
$amount1 = $payment_fetch['amount1']; 
$currency1 = $payment_fetch['currency1']; 
$amount2 = $payment_fetch['amount2'];
$currency2 = $payment_fetch['currency2']; 
$transaction_id= $payment_fetch['transaction_id'];
$order_id = $payment_fetch['custom']; 
$my_username = "farazrabbani";

//validate request if match with order
if ($my_username == $merchant_username && $token_status == true)
{
    $status="Processing";
    
$update=$conn->prepare("UPDATE `orders` SET `status`=?,`expected_amount`=?,`paid_amount`=?,`transaction_id`=? WHERE `order_id`=?");
$update->bindParam(1,$status);
$update->bindParam(2,$amount1);
$update->bindParam(3,$amount2);
$update->bindParam(4,$transaction_id);
$update->bindParam(5,$order_id);
$update->execute();

$fetch=$conn->prepare("SELECT * FROM `order` WHERE `order_id`=?");
$fetch->bindParam(1,$order_id);
$fetch->execute();
while($row = $fetch->fetch(PDO :: FETCH_ASSOC))
{
    $email=$row['email'];
   
    $mail->addAddress($email);
       $mail->isHTML(true);
       $mail->Subject = 'Order Payment Successful';
       $mail->Body = '<h3>Order Id : '.$order_id.',</h3><br><b>Your Order Has been Placed.</b><br><p>We will start processing your order after successful payment</p><br><p style="color:red";>Note : Order will be Cancelled if Payment not Done within 30 minutes,You can Place an order Again</p>';
       $mail->send();

}

}
?>`

**Comment by ourtecads** [comment]
you have to make sure what error occurs, with that you can try to make an error log when it fails to send an email, use the try function by writing the code as below

	try {
			$mail=new PHPMailer(true);
			$mail->isSMTP();
			$mail->Host = 'my host';
			$mail->SMTPAuth = true;
			$mail->Username = 'my username';
			$mail->Password = 'my password';
			$mail->SMTPSecure = 'ssl';
			$mail->Port = 465;
			$mail->setFrom('[admin@domain.com](mailto:admin@domain.com)', 'Faraz ');

			$mail->addAddress($email);
			$mail->isHTML(true);
			$mail->Subject = 'Order Payment Successful';
			$mail->Body = '<h3>Order Id : '.$order_id.',</h3><br><b>Your Order Has been Placed.</b><br><p>We will start processing your order after successful payment</p><br><p style="color:red";>Note : Order will be Cancelled if Payment not Done within 30 minutes,You can Place an order Again</p>';
			$mail->send();
			return true;
		} catch (phpmailerException $e) {
			error_log($mail->ErrorInfo);
			return false;
		} catch (Exception $e) {
			error_log($mail->ErrorInfo);
			return false;
		}

to see the error logs
There are two possible values for error_log: a custom log file and the syslog. If the syslog is used, then all PHP errors will be sent directly to the default system log file—in Linux, this is typically /var/log/syslog. The more manageable method is to use a custom log file. By doing this, you can isolate your PHP application's logs from the rest of the system logs, which can make debugging issues significantly easier.

**Comment by Farazrabbani4687** [comment]
Hay,Thank you so much my fetch query was wrong so it caused these problem,thank you so much for helping me out.Really Thank you so much
